spring.application.name=red_social_backend

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/redsocial_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret.key = z2n8xK7fR9vM4pQ6sT1uW3yX5zB8eG1hJ4kM7nQ9rU2vX5yA8dBfEjHmKpMsPvSt
